import re
import os.path

path = os.getcwd()
fileiist = os.listdir(f"{path}/번역본")

for i in fileiist:
    ReadFile = open(f"{path}/번역본/{i}", 'r' , encoding='UTF-16')
    ReadFile2 = open(f"{path}/시스템 문장 추출본/{i}", 'r' , encoding='UTF-16LE')
    WriteFile = open(f"{path}/최종 결과물/{i}", 'w', encoding='UTF-16')
    lines = ReadFile.readlines()

    a1 = re.compile('jap')
    a2 = re.compile(' ')
    a3 = re.compile(',')
    a4 = re.compile('~')

    b0 = re.compile('.*ANI.*')

    b1 = re.compile('衝撃')
    b2 = re.compile('火の粉')
    b3 = re.compile('パンチ')
    b4 = re.compile('爆発')
    b5 = re.compile('発光')
    b6 = re.compile('ハルキラキラ')
    b7 = re.compile('変身解除')
    b8 = re.compile('オーラ青')
    b9 = re.compile('飛散')
    b10 = re.compile('発動')
    b11 = re.compile('魔法攻撃')
    b12 = re.compile('渦巻き')
    b13 = re.compile('ビーム')
    b14 = re.compile('炎上')
    b15 = re.compile('空気')
    b16 = re.compile('空間')
    b17 = re.compile('連撃')
    b18 = re.compile('集束')
    b19 = re.compile('ライン上')
    b20 = re.compile('網目フラッシュ')
    b21 = re.compile('オーラ')
    b22 = re.compile('変身')
    b23 = re.compile('粒子青')
    b24 = re.compile('突風左')
    b25 = re.compile('上昇斜め')
    b26 = re.compile('風圧')
    b27 = re.compile('プラズマ緑')
    b28 = re.compile('網目')
    b29 = re.compile('上昇')
    b30 = re.compile('星')
    b31 = re.compile('デコピン')

    for j in lines:
        sss = ReadFile2.readline().strip("\n")
        c1 = re.sub(a1, 'kor', j)
        c2 = re.sub(a2, '^', c1)
        c3 = re.sub(a3, '、', c2)
        c4 = re.sub(a4, '～', c3)
        
        if b0.search(j):
            d1 = re.sub(b0, sss, j)
            d2 = re.sub(b1, 'eff1', d1)
            d3 = re.sub(b2, 'eff2', d2)
            d4 = re.sub(b3, 'eff3', d3)
            d5 = re.sub(b4, 'eff4', d4)
            d6 = re.sub(b5, 'eff5', d5)
            d7 = re.sub(b6, 'eff6', d6)
            d8 = re.sub(b7, 'eff7', d7)
            d9 = re.sub(b8, 'eff8', d8)
            d10 = re.sub(b9, 'eff9', d9)
            d11 = re.sub(b10, 'eff10', d10)
            d12 = re.sub(b11, 'eff11', d11)
            d13 = re.sub(b12, 'eff12', d12)
            d14 = re.sub(b13, 'eff13', d13)
            d15 = re.sub(b14, 'eff14', d14)
            d16 = re.sub(b15, 'eff15', d15)
            d17 = re.sub(b16, 'eff16', d16)
            d18 = re.sub(b17, 'eff17', d17)
            d19 = re.sub(b18, 'eff18', d18)
            d20 = re.sub(b19, 'eff19', d19)
            d21 = re.sub(b20, 'eff20', d20)
            d22 = re.sub(b21, 'eff21', d21)
            d23 = re.sub(b22, 'eff22', d22)
            d24 = re.sub(b23, 'eff23', d23)
            d25 = re.sub(b24, 'eff24', d24)
            d26 = re.sub(b25, 'eff25', d25)
            d27 = re.sub(b26, 'eff26', d26)
            d28 = re.sub(b27, 'eff27', d27)
            d29 = re.sub(b28, 'eff28', d28)
            d30 = re.sub(b29, 'eff29', d29)
            d31 = re.sub(b30, 'eff30', d30)
            contents = re.sub(b31, 'eff31', d31)
        else:
            contents = c4
        WriteFile.write(contents)
WriteFile.close()